# Top-level configuration
name = "cf-workers-status-page"
main = "index.js"
compatibility_date = "2022-07-12"
workers_dev = true

[env.production]
kv_namespaces = [
  { binding = "cf-workers-status-page", id = "6f1034edf2fa40cfb7319e76839ce528" }
]

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"

